version: '3.2'

volumes:
  tmp-data:
  redis-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      HOME: /tmp
      GOPATH: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    networks:
      - pesto
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGERS_USER: pesto
      POSTGERS_NAME: pesto
      POSTGRES_PASSWORD: pesto
      PGDATA: /storage/postgres-data
    volumes:
      - postgres:/storage/postgres-data
    ports:
      - "5433:5433"

    networks:
      - pesto


networks:
  pesto:
