version: '3.2'

volumes:
  tmp-data:
  redis-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      HOME: /tmp
      GOPATH: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    networks:
      - pesto
    depends_on:
      - postgres

  postgres:
    image: redis:5.0.7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data:cached
    networks:
      - pesto


networks:
  pesto:
